### ISSUE TITLE
Docker image 2023.12.01 version is upgraded to 2023.12.08 version, rutorrent cannot be used normally

### ISSUE THREAD

**Issue by lottelucky** [mondediefr/docker-rutorrent#112] opened 2024-01-12 02:01 UTC
Hello, Mondediefr.
I have been using your rutorrent docker project, but since the update to the 2023.12.08 version, my rutorrent can't start normally. The specific phenomenon is that after the transfer, an error is reported, rutorrent cannot start, and the plug-ins in the log column do not start normally. But I can only return to the 2023.12.01 version, and restore the content of the local config folder corresponding to the docker at the same time, so that it can be used normally. Please tell me, I don't know what has changed in your 12.08 version, so I can't use it after upgrading from version 12.01? In this case, what should I do?

**Comment by Rathorian** [comment] 2024-01-12 05:32
Hi,

What would have been nice is to give us the error message(s).

But during the period of December 9, we updated the PHP version and removed a plugin that is no longer maintained.

I suggest you turn off your container, delete the container.
Move and save your "/config" folder to another location.
Download the latest version of the image and start it.

No reason why it wouldn't work afterwards.

**Comment by lottelucky** [comment] 2024-01-12 05:38
Which plugin did you remove that is no longer maintained? I suspect that the original settings left over from this plugin caused the startup failure.

**Comment by Rathorian** [comment] 2024-01-12 05:50
> Which plugin did you remove that is no longer maintained? I suspect that the original settings left over from this plugin caused the startup failure.

You can see it on Github....
https://github.com/mondediefr/docker-rutorrent/commit/8d722688f8da867b79dda96077631264d4b5f00a

**Comment by lottelucky** [comment] 2024-01-12 07:26
I used the latest image and created the latest container based on it, but after starting, the system reported "Request rTorrent timed out."

The script to create the container is as follows:

docker run --name rutorrent -dt \
  --restart=always \
  -e UID=1026 \
  -e GID=101 \
  -e PORT_RTORRENT=27111 \
  -p 9191:8080 \
  -p 27111:27111 \
  -v /volume1/docker/rutorrent/config:/config \
  -v /volume1/docker/rutorrent/data:/data \
  mondedie/rutorrent:latest

By the way, let's talk about my environment.
Synology DS716 + II, DSM 6.2, DOCKER version is 20.10.3

**Comment by Rathorian** [comment] 2024-01-12 09:08
I also have a DS716 +II, I launched the image and the container starts without any errors.

<a href="https://ibb.co/N93b6k2"><img src="https://i.ibb.co/N93b6k2/Sans-titre.png" alt="Sans-titre" border="0"></a>

**Comment by Rathorian** [comment] 2024-01-13 05:34
> I used the latest image and created the latest container based on it, but after starting, the system reported "Request rTorrent timed out."
> 
> The script to create the container is as follows:
> 
> docker run --name rutorrent -dt --restart=always -e UID=1026 -e GID=101 -e PORT_RTORRENT=27111 -p 9191:8080 -p 27111:27111 -v /volume1/docker/rutorrent/config:/config -v /volume1/docker/rutorrent/data:/data mondedie/rutorrent:latest
> 
> By the way, let's talk about my environment. Synology DS716 + II, DSM 6.2, DOCKER version is 20.10.3

Hi,

By searching a little more on my NAS, I actually found the error that you reported on the ruTorrent interface.
I find it strange because on a Proxmox Debian vm, I have no problem.
At the moment, I don't know where it comes from.

**Comment by lottelucky** [comment] 2024-01-13 06:53
Thank you very much for testing in my hardware and software environment. I'll give you another clue: I used another image on the DOCKER HUB yesterday, crazymax/rtorrent-rutorrent, and it works fine under my synology DS716 + II. I checked his linux version and PHP version, which seem to be similar to what you are using, both of which are the latest versions.

**Comment by Rathorian** [comment] 2024-01-13 09:14
> Thank you very much for testing in my hardware and software environment. I'll give you another clue: I used another image on the DOCKER HUB yesterday, crazymax/rtorrent-rutorrent, and it works fine under my synology DS716 + II. I checked his linux version and PHP version, which seem to be similar to what you are using, both of which are the latest versions.
> 
> However, I still like your work, which is simple and practical, so I hope you can find the bug and eliminate it.

It just had an automatic update on the image to update the packages 1 time per week. By downloading this latest update, the bug disappeared on my side.

Can you check on your side?

**Comment by lottelucky** [comment] 2024-01-13 14:02
I pulled the latest mirror again, and it seems normal to use it at present, thank you for your guidance!
In addition, can you update the new version of rutorrent, that is, the 4.2.10 version, thank you!

**Comment by Rathorian** [comment] 2024-01-13 16:41
> I pulled the latest mirror again, and it seems normal to use it at present, thank you for your guidance! In addition, can you update the new version of rutorrent, that is, the 4.2.10 version, thank you!

If the problem is also solved for you, that's great.

Regarding the version of ruTorrent, we are already at version 4.2.10, take a look : https://github.com/mondediefr/docker-rutorrent/blob/c3f7c9066f96f6479f17846cb7bb11e045239bb7/Dockerfile#L31

I guess the problem is with the latest ruTorrent update at https://github.com/Novik/ruTorrent because I checked inside the container and we are in 4.2.10.

Probably a display bug on their part but which has not yet been resolved by them.

**Comment by lottelucky** [comment] 2024-01-14 00:30
Good. After the novik project fixes this problem, the version display problem will be solved naturally.
Thank you again for your hard work. I will keep up with your project!

**Comment by Rathorian** [comment] 2024-01-14 07:00
> Good. After the novik project fixes this problem, the version display problem will be solved naturally. Thank you again for your hard work. I will keep up with your project!

Yesterday, I made a Pull Request on: https://github.com/Novik/ruTorrent/pull/2628 to resolve the version display problem.

It has been validated but I don't think they will release a new release for it.

Therefore, either you wait for the next release of ruTorrent so that it displays correctly, or you do like me, you modify the "/rutorrent/app/js/webui.js" file yourself inside your docker container.

**Closed** 2024-01-20 15:36 UTC
Labels: bug
